dataScienceCluster:
  components:
    kserve:
      modelsAsService:
        managementState: Managed

gateways:
  maasDefaultGateway:
    useRoute: true
    certificate:
      create: false
  openshiftAiInference:
    create: true
    useRoute: true
    certificate:
      create: false
